[package]
name = "wain"
version = "0.0.0"
authors = ["rhysd <lin90162@yahoo.co.jp>"]
edition = "2018"
description = "WIP"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
