[package]
name = "wain"
version = "0.0.0"
authors = ["rhysd <lin90162@yahoo.co.jp>"]
edition = "2018"
description = "WIP"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "wain"

[dependencies]
wain-ast = { path = "./wain-ast" }
wain-wat = { path = "./wain-wat" }

[workspace]
members = [
    ".",
    "wain-ast",
    "wain-wat",
]
