[package]
name = "wain"
version = "0.0.0"
authors = ["rhysd <lin90162@yahoo.co.jp>"]
edition = "2018"
description = "WIP"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "wain"

[features]
default = ["binary", "text"]
binary = ["wain-syntax-binary"]
text = ["wain-syntax-text"]

[dependencies]
wain-ast = { path = "./wain-ast" }
wain-syntax-text = { path = "./wain-syntax-text", optional = true }
wain-syntax-binary = { path = "./wain-syntax-binary", optional = true }
wain-validate = { path = "./wain-validate" }
wain-exec = { path = "./wain-exec" }

[workspace]
members = [
    ".",
    "wain-ast",
    "wain-syntax-text",
    "wain-syntax-binary",
    "wain-validate",
    "wain-exec",
]
