name: CI
on: [push, pull_request]

jobs:
  unit-test:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        run: |
          rustup update stable
          rustup default stable
          rustc --version
          cargo --version
      - name: Run tests
        env:
          RUST_BACKTRACE: 1
        run: cargo test --color always --all
      - name: Build sources
        run: cargo build --color always
      - name: Run hello.wasm for sanity test
        run: cargo run -- examples/hello/hello.wasm
      - name: Run hello.wat for sanity test
        run: cargo run -- examples/hello/hello.wat
  linter:
    name: Clippy and Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: |
          rustup component add rustfmt clippy
          cargo fmt --version
          cargo clippy --version
      - run: cargo fmt -- --color always --check
      - run: cargo clippy --color always -- -D warnings
